config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :des_user_session
  end

  resources :users

  resources :photos do

    resources :likes
    resources :comments

    member do
      post :subscribe
      post :unsubscribe
    end

  end

  root 'photos#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo, :counter_cache => true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo, :counter_cache => true

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates_presence_of :user_id, :photo
  belongs_to :user
  has_many :likes
  has_many :like_photos, :through =>:likes, :source => "user"

  has_many :subscriptions
  has_many :subscribed_photos, :through =>:subscriptions, :source => "user"

  has_many :comments, :dependent => :destroy


  #paperclip
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  def find_like_by_user(user)
    self.likes.where( :user_id => user.id ).first
  end

  def can_delete_by?(current_user)
    user == current_user
  end



end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :photos
  has_many :comments, :dependent => :destroy

  has_many :likes
  has_many :like_photos, :through =>:likes, :source => "photo"

  has_many :subscriptions
  has_many :subscribed_photos, :through =>:subscriptions, :source => "photo"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]



  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      Rails.logger.info('==========')
      Rails.logger.info(auth)
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      user.fb_token = auth.credentials.token
      user.fb_expires_at = auth.credentials.expires_at
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  protected

  # def require_login
  #   unless current_user
  #     flash[:alert] = "Login Required"
  #     redirect_to root_path
  #     return
  #   end
  # end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.photo_id = params[:photo_id]
    @comment.user = current_user
    @comment.save
    # redirect_to :back
    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @comment = Comment.find( params[:id] )
    @comment.delete
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:photo_id, :content)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_photo

  def create
    @photos = Photo.all
    @photo = Photo.find(params[:photo_id])

    if @photo.find_like_by_user(current_user)
    else
      Like.create(:photo => @photo, :user => current_user)
    end
    # redirect_to root_url

    respond_to do |format|
      format.html { redirect_to :back }
      format.js {
        @photo.reload
        render :template => "likes/reload"
      }
    end

  end

  def destroy

    like = current_user.likes.find(params[:id])
    if like
      like.destroy
    end
    # redirect_to root_url

    respond_to do |format|
      format.html { redirect_to :back }
      format.js {
        @photo.reload
        render :template => "likes/reload"
      }
    end

  end

  private

  def set_photo
    @photos = Photo.all
    @photo = Photo.find(params[:photo_id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController


  def index
    @photos = Photo.all.order("updated_at DESC")
    @photo = Photo.new
    # @comment = Comment.new
  end


  def create
    # @photo = Photo.new(photo_params)
    # @photo.user = current_user
    # @photo.save
    current_user.photos.create(photo_params)
    redirect_to :back
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy if @photo.can_delete_by?(current_user)
    redirect_to :back
  end

  def subscribe
    @photo = Photo.find( params[:id] )

    existing_subscription = @photo.find_subscription_by_user(current_user)
    unless existing_subscription
      @subscription = Subscription.create( :user => current_user, :photo => @photo)
    end

    redirect_to :back
  end

  def unsubscribe
    @photo = Photo.find( params[:id] )
    existing_subscription = @photo.find_subscription_by_user(current_user)

    existing_subscription.destroy
    redirect_to :back
  end

  protected

  def photo_params
    params.require(:photo).permit(:photo, :description)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?

      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated

      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  protected

  def after_sign_in_path_for(resource_or_scope)
    photos_url
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @photo = Photo.all
  end

  def create
    @user = User.create( user_params )
  end



  private

  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.

  def user_params
    params.require(:user).permit(:photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_show.html.erb
<% photo.comments.order("updated_at DESC").each do |comment| %>
  <h4 id="comment-<%= comment.id %> " class="comment"><%= comment.content %></h4>
  <%= link_to "X", photo_comment_path(photo, comment), :method => :delete, :remote => true, :class => "btn btn-danger" %>
<% end %>

app/views/comments/create.js.erb
$('#photo-comment-<%= @comment.photo.id %>')
.prepend("<h4 id=\"comment-<%= @comment.id %>\" class=\"comment\"><%= @comment.content %></h4><%= j link_to 'X', photo_comment_path(@comment.photo, @comment), :method => :delete, :remote => true, :class => 'btn btn-danger' %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HwPhoto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--   <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->


<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Photo Social</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <ul class="nav navbar-nav navbar-right">

      <% if !current_user %>
          <li><%= link_to('註冊', new_registration_path(:user)) %></li>
          <li><%= link_to('登入', new_session_path(:user)) %></li>
      <% end %>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">

          <% if current_user %>
            <%= current_user.name %>
          <% else %>
            <%= "dropdown" %>
          <% end %>

          <b class="caret"></b></a>

        <ul class="dropdown-menu">
          <% if current_user %>
            <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
            <li><%= link_to('修改密碼', edit_registration_path(:user)) %></li>
          <% end %>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>






  <%= yield %>

</body>
</html>

app/views/likes/_show.html.erb
<%= photo.likes_count %>
<% if current_user %>
  <% like = photo.find_like_by_user(current_user) %>
  <% if like %>
    <%= link_to "unlike", photo_like_path(photo, like), :method => :delete, :class => "btn btn-danger", :remote => true %>
  <% else %>
    <%= link_to "like", photo_likes_path(photo), :method => :post, :class => "btn btn-danger", :remote => true %>
  <% end %>
<% end %>

app/views/likes/reload.js.erb
$("#photo-like-<%= @photo.id %>").html("<%= j(render :partial => "show", :locals => { :photo => @photo, :like => @like } ) %>");

app/views/photos/index.html.erb
<% if current_user %>
  <%= form_for @photo, :url => photos_path, :html => { :multipart => true } do |form| %>
    <%= form.file_field :photo %> <br>
    <%= form.text_area "description" %> <br>
    <%= form.submit "submit", :class =>"btn btn-primary" %>
  <% end %>
<% end %>


<!-- 列出所有photo依updated_at排序 -->

<% @photos.each do |photo| %>
  <div class="p">
    Created by: <%= photo.user.name %> <br>
    <%= image_tag( photo.photo(:original) ) %>
    <%= link_to "刪除", photo_path(photo), :method => :delete, :class => "btn btn-danger" %>

    <%= link_to "訂閱", photo_path(photo), :method => :delete, :class => "btn btn-danger" %>

    <div id="photo-like-<%= photo.id %>">
      <%= render :partial => "likes/show", :locals => { :photo => photo } %>
    </div>

    <h3>Description: <%= photo.description %></h3>


    <%= form_for Comment.new, :url => photo_comments_path(photo), :remote => true  do |f| %>
      <%= f.text_area :content, :placeholder => "回覆.." %>
      <%= f.submit "submit", :class =>"btn btn-primary" %>
    <% end %>

    <div id="photo-comment-<%= photo.id %>">
      <%= render :partial => "comments/show", :locals => { :photo => photo } %>
    </div>


  </div>
<% end %>